/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.Control;
import Model.Usuario;

/**
 *
 * @author guilherme
 */
public class MenuUI extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuUI() {
        initComponents();
/*     Para não aparecer os nomes padrões das labels, eu apaguei todos os valores do resumo */
        id_text_seuNome.setText("");
        id_text_nome.setText("");
        
        id_text_suaIdade.setText("");
        id_text_anos.setText("");
        
        id_text_seuSexo.setText("");
        id_text_sexo.setText("");
        
        id_text_seucpf.setText("");
        id_text_cpf.setText("");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        id_button_salvar = new javax.swing.JButton();
        id_input_nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_input_idade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        id_radio_Masc = new javax.swing.JRadioButton();
        id_radio_Fem = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id_text_seuNome = new javax.swing.JLabel();
        id_text_nome = new javax.swing.JLabel();
        id_text_anos = new javax.swing.JLabel();
        id_text_seuSexo = new javax.swing.JLabel();
        id_text_sexo = new javax.swing.JLabel();
        id_text_suaIdade = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        id_input_cpf = new javax.swing.JTextField();
        id_text_seucpf = new javax.swing.JLabel();
        id_text_cpf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite sua idade:");

        id_button_salvar.setText("Salvar");
        id_button_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_button_salvarActionPerformed(evt);
            }
        });

        id_input_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_input_nomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Digite seu nome: ");

        id_input_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_input_idadeActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        buttonGroup1.add(id_radio_Masc);
        id_radio_Masc.setText("Masculino");
        id_radio_Masc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_radio_MascActionPerformed(evt);
            }
        });

        buttonGroup1.add(id_radio_Fem);
        id_radio_Fem.setText("Feminino");

        jLabel4.setText("CADASTRO DE PESSOAS");

        jLabel5.setText("Resumo: ");

        id_text_seuNome.setText("jLabel6");

        id_text_nome.setText("jLabel6");

        id_text_anos.setText("jLabel6");

        id_text_seuSexo.setText("jLabel6");

        id_text_sexo.setText("jLabel6");

        id_text_suaIdade.setText("jLabel6");

        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Digite seu CPF:");

        id_text_seucpf.setText("jLabel7");

        id_text_cpf.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel4)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id_input_nome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(id_input_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_radio_Masc)
                            .addComponent(id_radio_Fem)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(id_input_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(id_text_seuSexo)
                    .addComponent(id_text_seucpf)
                    .addComponent(id_text_suaIdade)
                    .addComponent(id_text_seuNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_text_nome)
                    .addComponent(id_text_anos)
                    .addComponent(id_text_sexo)
                    .addComponent(id_text_cpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(318, 318, 318))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(id_button_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_input_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_input_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_radio_Masc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id_radio_Fem)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_input_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_text_nome)
                            .addComponent(id_text_seuNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_text_anos)
                            .addComponent(id_text_suaIdade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_text_sexo)
                            .addComponent(id_text_seuSexo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_text_cpf)
                            .addComponent(id_text_seucpf))
                        .addContainerGap(107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(id_button_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_input_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_input_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_input_nomeActionPerformed

    private void id_input_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_input_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_input_idadeActionPerformed

    private void id_button_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_button_salvarActionPerformed

    Control control = new Control();
    Usuario usuario = new Usuario();
    control.salvar();
    
     
     
        
 
        
    }//GEN-LAST:event_id_button_salvarActionPerformed

    private void id_radio_MascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_radio_MascActionPerformed
    }//GEN-LAST:event_id_radio_MascActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JButton id_button_salvar;
    public javax.swing.JTextField id_input_cpf;
    public javax.swing.JTextField id_input_idade;
    public javax.swing.JTextField id_input_nome;
    public javax.swing.JRadioButton id_radio_Fem;
    public javax.swing.JRadioButton id_radio_Masc;
    public javax.swing.JLabel id_text_anos;
    public javax.swing.JLabel id_text_cpf;
    public javax.swing.JLabel id_text_nome;
    public javax.swing.JLabel id_text_seuNome;
    public javax.swing.JLabel id_text_seuSexo;
    public javax.swing.JLabel id_text_seucpf;
    public javax.swing.JLabel id_text_sexo;
    public javax.swing.JLabel id_text_suaIdade;
    public javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
